name: babymilk2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  intl: ^0.18.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+4
  table_calendar: ^3.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
